Value::Object(HashMap::from([(
    "outer".into(),
    Value::Object(HashMap::from([(
        "inner".into(),
        Value::Object(HashMap::from([(
            "text".into(),
            Value::String("Deep\n".into()),
        )])),
    )])),
)]))
