/*
 * Generated by gen_fixtures.py - DO NOT EDIT
 */

#ifndef FIXTURES_GEN_H
#define FIXTURES_GEN_H

#include "yay.h"
#include <math.h>

typedef struct {
    const char *name;
    const char *yay_source;
    yay_value_t *(*make_expected)(void);
} test_fixture_t;

typedef struct {
    const char *name;
    const char *original_name;
    const char *nay_source;
    size_t nay_len;
    const char *error_pattern;
} error_fixture_t;

static yay_value_t *make_expected_array_inline_apostrophe(void) {
    return YAY_ARRAY(
    yay_string("I'm getting better!"),
    yay_string("No you're not."),
    yay_string("I feel happy!")
);
}

static yay_value_t *make_expected_array_inline_bytearray(void) {
    return YAY_ARRAY(yay_bytes_from_hex("b0b5"), yay_bytes_from_hex("cafe"));
}

static yay_value_t *make_expected_array_inline_doublequote_escapes(void) {
    return YAY_ARRAY(yay_string("say \"hi\""), yay_string("x"));
}

static yay_value_t *make_expected_array_inline_doublequote(void) {
    return YAY_ARRAY(
    yay_string("And there was much rejoicing."),
    yay_string("yay.")
);
}

static yay_value_t *make_expected_array_inline_integers(void) {
    return YAY_ARRAY(yay_int(42), yay_int(404), yay_int(418));
}

static yay_value_t *make_expected_array_inline_nested(void) {
    return YAY_ARRAY(
    YAY_ARRAY(yay_string("I feel happy!"), yay_string("yay.")),
    YAY_ARRAY(
        yay_string("And there was much rejoicing."),
        yay_string("yay.")
    )
);
}

static yay_value_t *make_expected_array_inline_singlequote(void) {
    return YAY_ARRAY(yay_string("a"), yay_string("b"));
}

static yay_value_t *make_expected_array_multiline_named(void) {
    return YAY_OBJECT(
    "complaints", YAY_ARRAY(
        yay_string("I didn't vote for you."),
        yay_string("Help, help, I'm being repressed!")
    )
);
}

static yay_value_t *make_expected_array_multiline_nested_multiline_object(void) {
    return YAY_ARRAY(
    YAY_OBJECT("x", yay_int(10), "y", yay_int(20)),
    YAY_OBJECT("x", yay_int(30), "y", yay_int(40))
);
}

static yay_value_t *make_expected_array_multiline_nested(void) {
    return YAY_ARRAY(
    YAY_ARRAY(yay_string("a"), yay_string("b")),
    YAY_ARRAY(yay_int(1), yay_int(2))
);
}

static yay_value_t *make_expected_array_multiline_triple_nested(void) {
    return YAY_ARRAY(YAY_ARRAY(YAY_ARRAY(yay_string("hello"))));
}

static yay_value_t *make_expected_array_multiline(void) {
    return YAY_ARRAY(yay_int(5), yay_int(3));
}

static yay_value_t *make_expected_at_a_glance(void) {
    return YAY_OBJECT(
    "and-objects-too", YAY_OBJECT(
        "from-their-floating-friends", yay_float(6.283185307179586),
        "integers-are-distinct", yay_int(42)
    ),
    "arrays", YAY_ARRAY(
        yay_string("may"),
        yay_string("have"),
        yay_string("many"),
        yay_string("values")
    ),
    "block", YAY_OBJECT(
        "array", YAY_ARRAY(
            yay_string("But"),
            yay_string("this"),
            yay_string("one's")
        ),
        "bytes", yay_bytes_from_hex("b0b5c0fffefacade"),
        "object", YAY_OBJECT("mine", yay_null()),
        "string", yay_string("This is a string.\nThere are many like it.\n")
    ),
    "concatenated", yay_string("I'm not dead yet. I feel happy!"),
    "inline", YAY_OBJECT(
        "array", YAY_ARRAY(
            yay_float(INFINITY),
            yay_float(-INFINITY),
            yay_float(NAN)
        ),
        "bytes", yay_bytes_from_hex("f33dface"),
        "object", YAY_OBJECT("bigint", yay_int(1), "float64", yay_float(2.0)),
        "string", yay_string("is concise")
    ),
    "name with spaces", yay_string("works too"),
    "roses-are-red", yay_bool(true),
    "unicode-code-point", yay_string("😀"),
    "violets-are-blue", yay_bool(false)
);
}

static yay_value_t *make_expected_bigint_one(void) {
    return yay_int(1);
}

static yay_value_t *make_expected_boolean_false(void) {
    return yay_bool(false);
}

static yay_value_t *make_expected_boolean_true(void) {
    return yay_bool(true);
}

static yay_value_t *make_expected_bytearray_block_basic(void) {
    return yay_bytes_from_hex("b0b5c0ff");
}

static yay_value_t *make_expected_bytearray_block_comment_only(void) {
    return yay_bytes_from_hex("b0b5c0ff");
}

static yay_value_t *make_expected_bytearray_block_deeply_nested(void) {
    return YAY_OBJECT(
    "level1", YAY_OBJECT(
        "level2", YAY_OBJECT("data", yay_bytes_from_hex("b0b5c0ff"))
    )
);
}

static yay_value_t *make_expected_bytearray_block_hex_and_comment(void) {
    return yay_bytes_from_hex("b0b5c0ff");
}

static yay_value_t *make_expected_bytearray_block_nested_property(void) {
    return YAY_OBJECT(
    "outer", YAY_OBJECT("data", yay_bytes_from_hex("b0b5c0ffeefacade"))
);
}

static yay_value_t *make_expected_bytearray_block_property_comment(void) {
    return YAY_OBJECT("data", yay_bytes_from_hex("b0b5c0ff"));
}

static yay_value_t *make_expected_bytearray_block_property(void) {
    return YAY_OBJECT("data", yay_bytes_from_hex("b0b5c0ffeefacade"));
}

static yay_value_t *make_expected_bytearray_in_array(void) {
    return YAY_ARRAY(yay_bytes_from_hex("b0b5"), yay_bytes_from_hex("cafe"));
}

static yay_value_t *make_expected_bytearray_in_object(void) {
    return YAY_OBJECT(
    "a", yay_bytes_from_hex("b0b5"),
    "b", yay_bytes_from_hex("cafe")
);
}

static yay_value_t *make_expected_bytearray_inline_empty(void) {
    return yay_bytes_from_hex("");
}

static yay_value_t *make_expected_bytearray_inline_even(void) {
    return yay_bytes_from_hex("b0b5c0ffeefacade");
}

static yay_value_t *make_expected_bytearray_inline_named(void) {
    return YAY_OBJECT("data", yay_bytes_from_hex("b0b5c0ffeefacade"));
}

static yay_value_t *make_expected_integer_big_basic(void) {
    return yay_int(42);
}

static yay_value_t *make_expected_integer_big_negative(void) {
    return yay_int(-42);
}

static yay_value_t *make_expected_integer_big(void) {
    return yay_int(8675309);
}

static yay_value_t *make_expected_mixed_depth_nesting_1(void) {
    return YAY_OBJECT(
    "root", YAY_OBJECT(
        "a", YAY_ARRAY(yay_int(1), yay_int(2)),
        "b", YAY_OBJECT("c", YAY_ARRAY(yay_int(3)), "d", yay_int(4))
    )
);
}

static yay_value_t *make_expected_mixed_depth_nesting_2(void) {
    return YAY_ARRAY(
    YAY_OBJECT(
        "a", YAY_OBJECT("b", YAY_ARRAY(yay_int(1), yay_int(2))),
        "c", yay_int(3)
    ),
    YAY_ARRAY(
        yay_string("d"),
        YAY_OBJECT("e", YAY_OBJECT("f", yay_int(4)))
    )
);
}

static yay_value_t *make_expected_mixed_depth_nesting_3(void) {
    return YAY_OBJECT(
    "top", YAY_OBJECT(
        "list", YAY_ARRAY(
            YAY_OBJECT(
                "bytes", yay_bytes_from_hex("b0b5"),
                "tag", yay_string("x")
            ),
            YAY_OBJECT(
                "more", YAY_OBJECT("inner", yay_bytes_from_hex("0f0f"))
            )
        ),
        "solo", yay_int(1)
    )
);
}

static yay_value_t *make_expected_nesting_L0_bytes(void) {
    return yay_bytes_from_hex("b0b5");
}

static yay_value_t *make_expected_nesting_L0_false(void) {
    return yay_bool(false);
}

static yay_value_t *make_expected_nesting_L0_float(void) {
    return yay_float(3.14);
}

static yay_value_t *make_expected_nesting_L0_int(void) {
    return yay_int(42);
}

static yay_value_t *make_expected_nesting_L0_null(void) {
    return yay_null();
}

static yay_value_t *make_expected_nesting_L0_strdq(void) {
    return yay_string("hello");
}

static yay_value_t *make_expected_nesting_L0_strsq(void) {
    return yay_string("world");
}

static yay_value_t *make_expected_nesting_L0_true(void) {
    return yay_bool(true);
}

static yay_value_t *make_expected_nesting_L1_arr_inline(void) {
    return YAY_ARRAY(yay_int(42), yay_string("hello"), yay_bytes_from_hex("b0b5"));
}

static yay_value_t *make_expected_nesting_L1_arr_multi(void) {
    return YAY_ARRAY(yay_int(42), yay_string("hello"), yay_bytes_from_hex("b0b5"));
}

static yay_value_t *make_expected_nesting_L1_empty_arr(void) {
    return yay_array();
}

static yay_value_t *make_expected_nesting_L1_empty_obj(void) {
    return yay_object();
}

static yay_value_t *make_expected_nesting_L1_named_arr(void) {
    return YAY_OBJECT("a", YAY_ARRAY(yay_int(42)));
}

static yay_value_t *make_expected_nesting_L1_obj_inline(void) {
    return YAY_OBJECT("a", yay_int(42), "b", yay_string("hello"));
}

static yay_value_t *make_expected_nesting_L1_obj_multi(void) {
    return YAY_OBJECT(
    "a", yay_int(42),
    "b", yay_string("hello"),
    "c", yay_bytes_from_hex("b0b5")
);
}

static yay_value_t *make_expected_nesting_L2_arr_in_arr_inline(void) {
    return YAY_ARRAY(
    YAY_ARRAY(yay_int(42), yay_int(42)),
    YAY_ARRAY(yay_string("hello"), yay_string("hello"))
);
}

static yay_value_t *make_expected_nesting_L2_arr_in_arr_multi(void) {
    return YAY_ARRAY(
    YAY_ARRAY(yay_int(42), yay_int(42)),
    YAY_ARRAY(yay_string("hello"), yay_string("hello"))
);
}

static yay_value_t *make_expected_nesting_L2_arr_in_obj_inline(void) {
    return YAY_OBJECT(
    "a", YAY_ARRAY(yay_int(42), yay_int(42)),
    "b", YAY_ARRAY(yay_string("hello"), yay_string("hello"))
);
}

static yay_value_t *make_expected_nesting_L2_arr_in_obj_multi(void) {
    return YAY_OBJECT("items", YAY_ARRAY(yay_int(42), yay_string("hello")));
}

static yay_value_t *make_expected_nesting_L2_blockbytes_in_obj(void) {
    return YAY_OBJECT("data", yay_bytes_from_hex("b0b5"));
}

static yay_value_t *make_expected_nesting_L2_blockstr_in_obj(void) {
    return YAY_OBJECT("message", yay_string("Hello\n"));
}

static yay_value_t *make_expected_nesting_L2_empty_nested(void) {
    return YAY_OBJECT("a", yay_object(), "b", yay_array());
}

static yay_value_t *make_expected_nesting_L2_obj_in_arr_multi(void) {
    return YAY_ARRAY(
    YAY_OBJECT("a", yay_int(42), "b", yay_string("hello")),
    YAY_OBJECT("c", yay_int(42))
);
}

static yay_value_t *make_expected_nesting_L2_obj_in_obj_inline(void) {
    return YAY_OBJECT(
    "a", YAY_OBJECT("x", yay_int(42)),
    "b", YAY_OBJECT("y", yay_string("hello"))
);
}

static yay_value_t *make_expected_nesting_L2_obj_in_obj_multi(void) {
    return YAY_OBJECT(
    "a", YAY_OBJECT("x", yay_int(42), "y", yay_string("hello")),
    "b", YAY_OBJECT("z", yay_int(42))
);
}

static yay_value_t *make_expected_nesting_L3_arr_arr_arr_inline(void) {
    return YAY_ARRAY(YAY_ARRAY(YAY_ARRAY(yay_string("hello"))));
}

static yay_value_t *make_expected_nesting_L3_arr_arr_arr(void) {
    return YAY_ARRAY(YAY_ARRAY(YAY_ARRAY(yay_int(42), yay_int(42))));
}

static yay_value_t *make_expected_nesting_L3_arr_arr_obj(void) {
    return YAY_ARRAY(
    YAY_ARRAY(YAY_OBJECT("a", yay_int(42), "b", yay_string("hello")))
);
}

static yay_value_t *make_expected_nesting_L3_arr_obj_arr(void) {
    return YAY_ARRAY(
    YAY_OBJECT("data", YAY_ARRAY(yay_int(42), yay_int(42))),
    YAY_OBJECT(
        "data", YAY_ARRAY(yay_string("hello"), yay_string("hello"))
    )
);
}

static yay_value_t *make_expected_nesting_L3_arr_obj_obj(void) {
    return YAY_ARRAY(YAY_OBJECT("nested", YAY_OBJECT("deep", yay_int(42))));
}

static yay_value_t *make_expected_nesting_L3_blockbytes_nested(void) {
    return YAY_OBJECT(
    "outer", YAY_OBJECT("inner", YAY_OBJECT("data", yay_bytes_from_hex("cafe")))
);
}

static yay_value_t *make_expected_nesting_L3_blockstr_nested(void) {
    return YAY_OBJECT(
    "outer", YAY_OBJECT("inner", YAY_OBJECT("text", yay_string("Deep\n")))
);
}

static yay_value_t *make_expected_nesting_L3_mixed_inline_in_multi(void) {
    return YAY_OBJECT(
    "items", YAY_ARRAY(
        YAY_ARRAY(yay_int(42), yay_int(42)),
        YAY_ARRAY(yay_string("hello"), yay_string("hello"))
    )
);
}

static yay_value_t *make_expected_nesting_L3_obj_arr_arr(void) {
    return YAY_OBJECT(
    "matrix", YAY_ARRAY(
        YAY_ARRAY(yay_int(42), yay_int(42)),
        YAY_ARRAY(yay_string("hello"), yay_string("hello"))
    )
);
}

static yay_value_t *make_expected_nesting_L3_obj_arr_obj(void) {
    return YAY_OBJECT(
    "items", YAY_ARRAY(
        YAY_OBJECT("name", yay_string("hello"), "value", yay_int(42)),
        YAY_OBJECT("name", yay_string("hello"), "value", yay_int(42))
    )
);
}

static yay_value_t *make_expected_nesting_L3_obj_obj_arr(void) {
    return YAY_OBJECT(
    "outer", YAY_OBJECT("inner", YAY_ARRAY(yay_int(42), yay_string("hello")))
);
}

static yay_value_t *make_expected_nesting_L3_obj_obj_obj(void) {
    return YAY_OBJECT(
    "a", YAY_OBJECT(
        "b", YAY_OBJECT("c", yay_int(42), "d", yay_string("hello"))
    )
);
}

static yay_value_t *make_expected_null_literal(void) {
    return yay_null();
}

static yay_value_t *make_expected_number_float_avogadro(void) {
    return yay_float(602200000000000000000000.0);
}

static yay_value_t *make_expected_number_float_exponent(void) {
    return YAY_OBJECT(
    "leading-dot", yay_float(50.0),
    "negative-exp", yay_float(0.0000314),
    "no-decimal", yay_float(600000000000000000000000.0),
    "positive-exp", yay_float(271000000.0),
    "scientific", yay_float(15000000000.0)
);
}

static yay_value_t *make_expected_number_float_grouped(void) {
    return yay_float(6.283185307179586);
}

static yay_value_t *make_expected_number_float_infinity(void) {
    return yay_float(INFINITY);
}

static yay_value_t *make_expected_number_float_leading_dot(void) {
    return yay_float(0.5);
}

static yay_value_t *make_expected_number_float_nan(void) {
    return yay_float(NAN);
}

static yay_value_t *make_expected_number_float_negative_infinity(void) {
    return yay_float(-INFINITY);
}

static yay_value_t *make_expected_number_float_negative_zero(void) {
    return yay_float(-0.0);
}

static yay_value_t *make_expected_number_float_trailing_dot(void) {
    return yay_float(1.0);
}

static yay_value_t *make_expected_number_float(void) {
    return yay_float(6.283185307179586);
}

static yay_value_t *make_expected_object_deeply_nested_empty(void) {
    return YAY_OBJECT(
    "level1", YAY_OBJECT("level2", YAY_OBJECT("level3", yay_object()))
);
}

static yay_value_t *make_expected_object_inline_doublequote_key(void) {
    return YAY_OBJECT("*", yay_float(1.0));
}

static yay_value_t *make_expected_object_inline_empty(void) {
    return YAY_OBJECT("empty", yay_object());
}

static yay_value_t *make_expected_object_inline_integers(void) {
    return YAY_OBJECT("answer", yay_int(42), "error", yay_int(404));
}

static yay_value_t *make_expected_object_inline_mixed(void) {
    return YAY_OBJECT(
    "mood", yay_string("depressed"),
    "name", yay_string("Marvin")
);
}

static yay_value_t *make_expected_object_inline_nested(void) {
    return YAY_OBJECT(
    "air", YAY_ARRAY(yay_string("canned"), yay_string("Perri-Air")),
    "luggage", YAY_OBJECT("combination", yay_int(12345))
);
}

static yay_value_t *make_expected_object_inline_singlequote(void) {
    return YAY_OBJECT("*", yay_float(1.0));
}

static yay_value_t *make_expected_object_multiline_doublequote_key(void) {
    return YAY_OBJECT("key name", yay_int(1));
}

static yay_value_t *make_expected_object_multiline_nested(void) {
    return YAY_OBJECT(
    "parrot", YAY_OBJECT(
        "plumage", yay_string("beautiful"),
        "status", yay_string("pining for the fjords")
    )
);
}

static yay_value_t *make_expected_object_multiline_singlequote_key(void) {
    return YAY_OBJECT("key-name", yay_int(2));
}

static yay_value_t *make_expected_object_multiline(void) {
    return YAY_OBJECT("answer", yay_int(42), "error", yay_int(404));
}

static yay_value_t *make_expected_object_nested_empty_inline(void) {
    return YAY_OBJECT("outer", YAY_OBJECT("inner", yay_object()));
}

static yay_value_t *make_expected_object_nested_empty_property(void) {
    return YAY_OBJECT("outer", YAY_OBJECT("inner", yay_object()));
}

static yay_value_t *make_expected_string_block_deep_indent(void) {
    return YAY_OBJECT("message", yay_string("Line 1\n  Indented\nLine 2\n"));
}

static yay_value_t *make_expected_string_block_deeply_nested(void) {
    return YAY_OBJECT(
    "level1", YAY_OBJECT(
        "level2", YAY_OBJECT("text", yay_string("Hello\nWorld\n"))
    )
);
}

static yay_value_t *make_expected_string_block_empty_middle(void) {
    return yay_string("\nI'm getting better!\n\nNo you're not.\n");
}

static yay_value_t *make_expected_string_block_nested_in_object_and_array(void) {
    return YAY_OBJECT(
    "parrot", YAY_OBJECT(
        "condition", yay_string("No, no, it's just resting!\n"),
        "remarks", YAY_ARRAY(
            yay_string("Remarkable bird, the Norwegian Blue.\nBeautiful plumage, innit?\n"),
            yay_string("It's probably pining for the fjords.\nLovely plumage.\n")
        )
    )
);
}

static yay_value_t *make_expected_string_block_property_empty_middle(void) {
    return YAY_OBJECT(
    "message", yay_string("It's not pining!\n\nIt's passed on! This parrot is no more!\n")
);
}

static yay_value_t *make_expected_string_block_property_trailing_empty(void) {
    return YAY_OBJECT(
    "message", yay_string("By Grabthar's hammer... what a savings.\n"),
    "next", yay_int(1)
);
}

static yay_value_t *make_expected_string_block_property(void) {
    return YAY_OBJECT(
    "message", yay_string("By Grabthar's hammer, we live to tell the tale.\n")
);
}

static yay_value_t *make_expected_string_block_root_hash(void) {
    return yay_string("# this is not a comment\nit is content\n");
}

static yay_value_t *make_expected_string_block_root_next_line(void) {
    return yay_string("\nI've calculated your chance of survival,\nbut I don't think you'll like it.\n");
}

static yay_value_t *make_expected_string_block_root_same_line(void) {
    return yay_string("I think you ought to know I'm feeling very depressed.\nThis will all end in tears.\n");
}

static yay_value_t *make_expected_string_block_trailing_empty(void) {
    return yay_string("\nHello\n");
}

static yay_value_t *make_expected_string_inline_doublequote_apostrophe(void) {
    return yay_string("I'm getting better!");
}

static yay_value_t *make_expected_string_inline_doublequote_basic(void) {
    return yay_string("This will all end in tears.");
}

static yay_value_t *make_expected_string_inline_doublequote_escaped_quote(void) {
    return yay_string("He said \"yay.\" and left.");
}

static yay_value_t *make_expected_string_inline_doublequote_escapes(void) {
    return yay_string("\"\\/\b\f\n\r\t☺");
}

static yay_value_t *make_expected_string_inline_doublequote_space(void) {
    return yay_string(" ");
}

static yay_value_t *make_expected_string_inline_doublequote_unicode_emoji(void) {
    return yay_string("😀");
}

static yay_value_t *make_expected_string_inline_doublequote_unicode_surrogate_pair(void) {
    return yay_string("😀");
}

static yay_value_t *make_expected_string_inline_singlequote_basic(void) {
    return yay_string("Are you suggesting coconuts migrate?");
}

static yay_value_t *make_expected_string_inline_singlequote_doublequote(void) {
    return yay_string("He said \"yay.\" and left.");
}

static yay_value_t *make_expected_string_multiline_concat(void) {
    return YAY_OBJECT("confession", yay_string("I'm not dead yet. I feel happy!"));
}

static yay_value_t *make_expected_whitespace_leading_lines(void) {
    return yay_int(10);
}

static test_fixture_t test_fixtures[] = {
    {"array_inline_apostrophe", "[\"I'm getting better!\", \"No you're not.\", \"I feel happy!\"]\n", make_expected_array_inline_apostrophe},
    {"array_inline_bytearray", "[<b0b5>, <cafe>]\n", make_expected_array_inline_bytearray},
    {"array_inline_doublequote_escapes", "[\"say \\\"hi\\\"\", \"x\"]\n", make_expected_array_inline_doublequote_escapes},
    {"array_inline_doublequote", "[\"And there was much rejoicing.\", \"yay.\"]\n", make_expected_array_inline_doublequote},
    {"array_inline_integers", "[42, 404, 418]\n", make_expected_array_inline_integers},
    {"array_inline_nested", "[[\"I feel happy!\", \"yay.\"], [\"And there was much rejoicing.\", \"yay.\"]]\n", make_expected_array_inline_nested},
    {"array_inline_singlequote", "['a', 'b']\n", make_expected_array_inline_singlequote},
    {"array_multiline_named", "complaints:\n- \"I didn't vote for you.\"\n- \"Help, help, I'm being repressed!\"\n", make_expected_array_multiline_named},
    {"array_multiline_nested_multiline_object", "- x: 10\n  y: 20\n- x: 30\n  y: 40\n", make_expected_array_multiline_nested_multiline_object},
    {"array_multiline_nested", "- - \"a\"\n  - \"b\"\n- - 1\n  - 2\n", make_expected_array_multiline_nested},
    {"array_multiline_triple_nested", "- - - 'hello'\n", make_expected_array_multiline_triple_nested},
    {"array_multiline", "- 5\n- 3\n", make_expected_array_multiline},
    {"at_a_glance", "roses-are-red: true      # There is no \"yes\" or \"on\".\nviolets-are-blue: false  # Violets are violet.\narrays:\n  - \"may\"\n  - \"have\"\n  - \"many\"\n  - \"values\"\nand-objects-too:\n  integers-are-distinct: 42\n  from-their-floating-friends: 6.283 185 307 179 586  # digit grouping\ninline:\n  string: \"is concise\"\n  array: [infinity, -infinity, nan]\n  object: {bigint: 1, float64: 2.0}\n  bytes: <f33d face>\nblock:\n  string: `\n    This is a string.\n    There are many like it.\n  array:\n    - \"But\"\n    - \"this\"\n    - \"one's\"\n  object:\n    mine: null\n  bytes: >\n    b0 b5  c0 ff  # Bob's Coffee\n    fe fa  ca de  # Facade.\nconcatenated:\n  \"I'm not dead yet. \"\n  \"I feel happy!\"\nunicode-code-point: \"\\u{1F600}\"  # UTF-16 surrogates are inexpressible\n\"name with spaces\": 'works too'\n", make_expected_at_a_glance},
    {"bigint_one", "1\n", make_expected_bigint_one},
    {"boolean_false", "false\n", make_expected_boolean_false},
    {"boolean_true", "true\n", make_expected_boolean_true},
    {"bytearray_block_basic", "> b0b5\n  c0ff\n", make_expected_bytearray_block_basic},
    {"bytearray_block_comment_only", "> # header comment\n  b0b5 c0ff\n", make_expected_bytearray_block_comment_only},
    {"bytearray_block_deeply_nested", "level1:\n  level2:\n    data: >\n      b0b5 c0ff\n", make_expected_bytearray_block_deeply_nested},
    {"bytearray_block_hex_and_comment", "> b0b5 # first chunk\n  c0ff # second chunk\n", make_expected_bytearray_block_hex_and_comment},
    {"bytearray_block_nested_property", "outer:\n  data: >\n    b0b5 c0ff\n    eefa cade\n", make_expected_bytearray_block_nested_property},
    {"bytearray_block_property_comment", "data: > # raw bytes\n  b0b5 c0ff\n", make_expected_bytearray_block_property_comment},
    {"bytearray_block_property", "data: >\n  b0b5 c0ff\n  eefa cade\n", make_expected_bytearray_block_property},
    {"bytearray_in_array", "- <b0b5>\n- <cafe>\n", make_expected_bytearray_in_array},
    {"bytearray_in_object", "a: <b0b5>\nb: <cafe>\n", make_expected_bytearray_in_object},
    {"bytearray_inline_empty", "<>\n", make_expected_bytearray_inline_empty},
    {"bytearray_inline_even", "<b0b5c0ffeefacade>\n", make_expected_bytearray_inline_even},
    {"bytearray_inline_named", "data: <b0b5c0ffeefacade>\n", make_expected_bytearray_inline_named},
    {"integer_big_basic", "42\n", make_expected_integer_big_basic},
    {"integer_big_negative", "-42\n", make_expected_integer_big_negative},
    {"integer_big", "867 5309\n", make_expected_integer_big},
    {"mixed_depth_nesting_1", "root:\n  a:\n    - 1\n    - 2\n  b:\n    c:\n      - 3\n    d: 4\n", make_expected_mixed_depth_nesting_1},
    {"mixed_depth_nesting_2", "- a:\n    b:\n      - 1\n      - 2\n  c: 3\n- - \"d\"\n  - e:\n      f: 4\n", make_expected_mixed_depth_nesting_2},
    {"mixed_depth_nesting_3", "top:\n  list:\n    - bytes: <b0b5>\n      tag: \"x\"\n    - more:\n        inner: <0f0f>\n  solo: 1\n", make_expected_mixed_depth_nesting_3},
    {"nesting_L0_bytes", "<b0b5>\n", make_expected_nesting_L0_bytes},
    {"nesting_L0_false", "false\n", make_expected_nesting_L0_false},
    {"nesting_L0_float", "3.14\n", make_expected_nesting_L0_float},
    {"nesting_L0_int", "42\n", make_expected_nesting_L0_int},
    {"nesting_L0_null", "null\n", make_expected_nesting_L0_null},
    {"nesting_L0_strdq", "\"hello\"\n", make_expected_nesting_L0_strdq},
    {"nesting_L0_strsq", "'world'\n", make_expected_nesting_L0_strsq},
    {"nesting_L0_true", "true\n", make_expected_nesting_L0_true},
    {"nesting_L1_arr_inline", "[42, \"hello\", <b0b5>]\n", make_expected_nesting_L1_arr_inline},
    {"nesting_L1_arr_multi", "- 42\n- \"hello\"\n- <b0b5>\n", make_expected_nesting_L1_arr_multi},
    {"nesting_L1_empty_arr", "[]\n", make_expected_nesting_L1_empty_arr},
    {"nesting_L1_empty_obj", "{}\n", make_expected_nesting_L1_empty_obj},
    {"nesting_L1_named_arr", "a:\n  - 42\n", make_expected_nesting_L1_named_arr},
    {"nesting_L1_obj_inline", "{a: 42, b: \"hello\"}\n", make_expected_nesting_L1_obj_inline},
    {"nesting_L1_obj_multi", "a: 42\nb: \"hello\"\nc: <b0b5>\n", make_expected_nesting_L1_obj_multi},
    {"nesting_L2_arr_in_arr_inline", "[[42, 42], [\"hello\", \"hello\"]]\n", make_expected_nesting_L2_arr_in_arr_inline},
    {"nesting_L2_arr_in_arr_multi", "- - 42\n  - 42\n- - \"hello\"\n  - \"hello\"\n", make_expected_nesting_L2_arr_in_arr_multi},
    {"nesting_L2_arr_in_obj_inline", "{a: [42, 42], b: [\"hello\", \"hello\"]}\n", make_expected_nesting_L2_arr_in_obj_inline},
    {"nesting_L2_arr_in_obj_multi", "items:\n  - 42\n  - \"hello\"\n", make_expected_nesting_L2_arr_in_obj_multi},
    {"nesting_L2_blockbytes_in_obj", "data: >\n  b0b5\n", make_expected_nesting_L2_blockbytes_in_obj},
    {"nesting_L2_blockstr_in_obj", "message: `\n  Hello\n", make_expected_nesting_L2_blockstr_in_obj},
    {"nesting_L2_empty_nested", "a: {}\nb: []\n", make_expected_nesting_L2_empty_nested},
    {"nesting_L2_obj_in_arr_multi", "- a: 42\n  b: \"hello\"\n- c: 42\n", make_expected_nesting_L2_obj_in_arr_multi},
    {"nesting_L2_obj_in_obj_inline", "{a: {x: 42}, b: {y: \"hello\"}}\n", make_expected_nesting_L2_obj_in_obj_inline},
    {"nesting_L2_obj_in_obj_multi", "a:\n  x: 42\n  y: \"hello\"\nb:\n  z: 42\n", make_expected_nesting_L2_obj_in_obj_multi},
    {"nesting_L3_arr_arr_arr_inline", "- - - 'hello'\n", make_expected_nesting_L3_arr_arr_arr_inline},
    {"nesting_L3_arr_arr_arr", "- - [42, 42]\n", make_expected_nesting_L3_arr_arr_arr},
    {"nesting_L3_arr_arr_obj", "- - {a: 42, b: \"hello\"}\n", make_expected_nesting_L3_arr_arr_obj},
    {"nesting_L3_arr_obj_arr", "- data:\n    - 42\n    - 42\n- data:\n    - \"hello\"\n    - \"hello\"\n", make_expected_nesting_L3_arr_obj_arr},
    {"nesting_L3_arr_obj_obj", "- nested:\n    deep: 42\n", make_expected_nesting_L3_arr_obj_obj},
    {"nesting_L3_blockbytes_nested", "outer:\n  inner:\n    data: >\n      cafe\n", make_expected_nesting_L3_blockbytes_nested},
    {"nesting_L3_blockstr_nested", "outer:\n  inner:\n    text: `\n      Deep\n", make_expected_nesting_L3_blockstr_nested},
    {"nesting_L3_mixed_inline_in_multi", "items:\n  - [42, 42]\n  - [\"hello\", \"hello\"]\n", make_expected_nesting_L3_mixed_inline_in_multi},
    {"nesting_L3_obj_arr_arr", "matrix:\n  - - 42\n    - 42\n  - - \"hello\"\n    - \"hello\"\n", make_expected_nesting_L3_obj_arr_arr},
    {"nesting_L3_obj_arr_obj", "items:\n  - name: \"hello\"\n    value: 42\n  - name: \"hello\"\n    value: 42\n", make_expected_nesting_L3_obj_arr_obj},
    {"nesting_L3_obj_obj_arr", "outer:\n  inner:\n    - 42\n    - \"hello\"\n", make_expected_nesting_L3_obj_obj_arr},
    {"nesting_L3_obj_obj_obj", "a:\n  b:\n    c: 42\n    d: \"hello\"\n", make_expected_nesting_L3_obj_obj_obj},
    {"null_literal", "null\n", make_expected_null_literal},
    {"number_float_avogadro", "6.022e23\n", make_expected_number_float_avogadro},
    {"number_float_exponent", "scientific: 1.5e10\nnegative-exp: 3.14e-5\npositive-exp: 2.71e+8\nno-decimal: 6e23\nleading-dot: .5e2\n", make_expected_number_float_exponent},
    {"number_float_grouped", "6.283 185 307 179 586\n", make_expected_number_float_grouped},
    {"number_float_infinity", "infinity\n", make_expected_number_float_infinity},
    {"number_float_leading_dot", ".5\n", make_expected_number_float_leading_dot},
    {"number_float_nan", "nan\n", make_expected_number_float_nan},
    {"number_float_negative_infinity", "-infinity\n", make_expected_number_float_negative_infinity},
    {"number_float_negative_zero", "-0.0\n", make_expected_number_float_negative_zero},
    {"number_float_trailing_dot", "1.\n", make_expected_number_float_trailing_dot},
    {"number_float", "6.283185307179586\n", make_expected_number_float},
    {"object_deeply_nested_empty", "level1:\n  level2:\n    level3: {}\n", make_expected_object_deeply_nested_empty},
    {"object_inline_doublequote_key", "\"*\": 1.0\n", make_expected_object_inline_doublequote_key},
    {"object_inline_empty", "empty: {}\n", make_expected_object_inline_empty},
    {"object_inline_integers", "{answer: 42, error: 404}\n", make_expected_object_inline_integers},
    {"object_inline_mixed", "{name: 'Marvin', mood: 'depressed'}\n", make_expected_object_inline_mixed},
    {"object_inline_nested", "{luggage: {combination: 12345}, air: [\"canned\", \"Perri-Air\"]}\n", make_expected_object_inline_nested},
    {"object_inline_singlequote", "'*': 1.0\n", make_expected_object_inline_singlequote},
    {"object_multiline_doublequote_key", "\"key name\": 1\n", make_expected_object_multiline_doublequote_key},
    {"object_multiline_nested", "parrot:\n  status: \"pining for the fjords\"\n  plumage: \"beautiful\"\n", make_expected_object_multiline_nested},
    {"object_multiline_singlequote_key", "'key-name': 2\n", make_expected_object_multiline_singlequote_key},
    {"object_multiline", "answer: 42\nerror: 404\n", make_expected_object_multiline},
    {"object_nested_empty_inline", "outer:\n  inner: {}\n", make_expected_object_nested_empty_inline},
    {"object_nested_empty_property", "outer:\n  inner: {}\n", make_expected_object_nested_empty_property},
    {"string_block_deep_indent", "message: `\n    Line 1\n      Indented\n    Line 2\n", make_expected_string_block_deep_indent},
    {"string_block_deeply_nested", "level1:\n  level2:\n    text: `\n      Hello\n      World\n", make_expected_string_block_deeply_nested},
    {"string_block_empty_middle", "`\n  I'm getting better!\n\n  No you're not.\n", make_expected_string_block_empty_middle},
    {"string_block_nested_in_object_and_array", "parrot:\n  condition: `\n    No, no, it's just resting!\n\n  remarks:\n  - ` Remarkable bird, the Norwegian Blue.\n      Beautiful plumage, innit?\n\n  - ` It's probably pining for the fjords.\n      Lovely plumage.\n", make_expected_string_block_nested_in_object_and_array},
    {"string_block_property_empty_middle", "message: `\n  It's not pining!\n\n  It's passed on! This parrot is no more!\n", make_expected_string_block_property_empty_middle},
    {"string_block_property_trailing_empty", "message: `\n  By Grabthar's hammer... what a savings.\n\n\nnext: 1\n", make_expected_string_block_property_trailing_empty},
    {"string_block_property", "message: `\n  By Grabthar's hammer, we live to tell the tale.\n", make_expected_string_block_property},
    {"string_block_root_hash", "` # this is not a comment\n  it is content\n", make_expected_string_block_root_hash},
    {"string_block_root_next_line", "`\n  I've calculated your chance of survival,\n  but I don't think you'll like it.\n", make_expected_string_block_root_next_line},
    {"string_block_root_same_line", "` I think you ought to know I'm feeling very depressed.\n  This will all end in tears.\n", make_expected_string_block_root_same_line},
    {"string_block_trailing_empty", "`\n  Hello\n\n\n", make_expected_string_block_trailing_empty},
    {"string_inline_doublequote_apostrophe", "\"I'm getting better!\"\n", make_expected_string_inline_doublequote_apostrophe},
    {"string_inline_doublequote_basic", "\"This will all end in tears.\"\n", make_expected_string_inline_doublequote_basic},
    {"string_inline_doublequote_escaped_quote", "\"He said \\\"yay.\\\" and left.\"\n", make_expected_string_inline_doublequote_escaped_quote},
    {"string_inline_doublequote_escapes", "\"\\\"\\\\\\/\\b\\f\\n\\r\\t\\u{263A}\"\n", make_expected_string_inline_doublequote_escapes},
    {"string_inline_doublequote_space", "\" \"\n", make_expected_string_inline_doublequote_space},
    {"string_inline_doublequote_unicode_emoji", "\"😀\"\n", make_expected_string_inline_doublequote_unicode_emoji},
    {"string_inline_doublequote_unicode_surrogate_pair", "\"\\u{1F600}\"\n", make_expected_string_inline_doublequote_unicode_surrogate_pair},
    {"string_inline_singlequote_basic", "'Are you suggesting coconuts migrate?'\n", make_expected_string_inline_singlequote_basic},
    {"string_inline_singlequote_doublequote", "'He said \"yay.\" and left.'\n", make_expected_string_inline_singlequote_doublequote},
    {"string_multiline_concat", "confession:\n  \"I'm not dead yet. \"\n  \"I feel happy!\"\n", make_expected_string_multiline_concat},
    {"whitespace_leading_lines", "\n\n# Commentary here\n\n10\n\n\n# Comments there\n\n", make_expected_whitespace_leading_lines},
    {NULL, NULL, NULL}
};

#define TEST_FIXTURE_COUNT 117

static error_fixture_t error_fixtures[] = {
    {"array_inline_invalid_multiline", "array-inline-invalid-multiline.nay", "[\n  1,\n  2\n]\n", 13, "Unexpected newline in inline array at 1:1 of <array-inline-invalid-multiline.nay>"},
    {"array_inline_invalid_space_after_comma", "array-inline-invalid-space-after-comma.nay", "[1,  2]\n", 8, "Unexpected space after \",\" at 1:5 of <array-inline-invalid-space-after-comma.nay>"},
    {"array_inline_invalid_space_after_open", "array-inline-invalid-space-after-open.nay", "[ 1,2]\n", 7, "Unexpected space after \"[\" at 1:2 of <array-inline-invalid-space-after-open.nay>"},
    {"array_inline_invalid_space_before_close", "array-inline-invalid-space-before-close.nay", "[1,2 ]\n", 7, "Unexpected space before \"]\" at 1:5 of <array-inline-invalid-space-before-close.nay>"},
    {"array_inline_invalid_space_before_comma", "array-inline-invalid-space-before-comma.nay", "[1 ,2]\n", 7, "Unexpected space before \",\" at 1:3 of <array-inline-invalid-space-before-comma.nay>"},
    {"array_inline_invalid_tab", "array-inline-invalid-tab.nay", "[1,\0112]\n", 7, "Tab not allowed (use spaces) at 1:4 of <array-inline-invalid-tab.nay>"},
    {"array_inline_property_invalid_next_line", "array-inline-property-invalid-next-line.nay", "i:\n  [1, 2, 3]\n", 15, "Unexpected indent at 2:1 of <array-inline-property-invalid-next-line.nay>"},
    {"array_multiline_invalid_compact", "array-multiline-invalid-compact.nay", "-a\n-b\n-c\n", 9, "Expected space after \"-\" at 1:2 of <array-multiline-invalid-compact.nay>"},
    {"array_multiline_invalid_leading_space", "array-multiline-invalid-leading-space.nay", "-  1\n", 5, "Unexpected leading space at 1:1 of <array-multiline-invalid-leading-space.nay>"},
    {"array_multiline_invalid_nested_space", "array-multiline-invalid-nested-space.nay", "- -  a\n  - b\n", 13, "Unexpected space after \"-\" at 1:3 of <array-multiline-invalid-nested-space.nay>"},
    {"array_multiline_invalid_trailing_space", "array-multiline-invalid-trailing-space.nay", "- \n  1\n", 7, "Unexpected trailing space at 1:2 of <array-multiline-invalid-trailing-space.nay>"},
    {"array_multiline_nested_invalid_bare_word", "array-multiline-nested-invalid-bare-word.nay", "- - a\n  - b\n- - 1\n  - 2\n", 24, "Unexpected character \"a\" at 1:3 of <array-multiline-nested-invalid-bare-word.nay>"},
    {"blank_line_trailing_space", "blank-line-trailing-space.nay", "   \n", 4, "Unexpected trailing space at 1:3 of <blank-line-trailing-space.nay>"},
    {"bytearray_block_invalid_empty_leader", "bytearray-block-invalid-empty-leader.nay", ">\n  b0b5\n", 9, "Expected hex or comment in hex block"},
    {"bytearray_block_property_invalid_leader_next_line", "bytearray-block-property-invalid-leader-next-line.nay", "i:\n  >\n    cafe\n    babe\n", 25, "Unexpected indent at 2:1 of <bytearray-block-property-invalid-leader-next-line.nay>"},
    {"bytearray_block_property_invalid_same_line", "bytearray-block-property-invalid-same-line.nay", "data: > b0b5\n  c0ff\n", 20, "Expected newline after block leader in property"},
    {"bytearray_inline_invalid_hex_digit", "bytearray-inline-invalid-hex-digit.nay", "<deadbeefXX>\n", 13, "Invalid hex digit at 1:1 of <bytearray-inline-invalid-hex-digit.nay>"},
    {"bytearray_inline_invalid_unclosed_root", "bytearray-inline-invalid-unclosed-root.nay", "<\n  b0b5\n", 9, "Unmatched angle bracket at 1:1 of <bytearray-inline-invalid-unclosed-root.nay>"},
    {"bytearray_inline_invalid_unclosed", "bytearray-inline-invalid-unclosed.nay", "a: <\n  b0b5\n", 12, "Unmatched angle bracket at 1:4 of <bytearray-inline-invalid-unclosed.nay>"},
    {"bytearray_inline_odd", "bytearray-inline-odd.nay", "<a>\n", 4, "Odd number of hex digits in byte literal at 1:1 of <bytearray-inline-odd.nay>"},
    {"bytearray_inline_property_invalid_next_line", "bytearray-inline-property-invalid-next-line.nay", "i:\n  <cafe>\n", 12, "Unexpected indent at 2:1 of <bytearray-inline-property-invalid-next-line.nay>"},
    {"bytearray_invalid_uppercase_hex", "bytearray-invalid-uppercase-hex.nay", "<DEADBEEF>\n", 11, "Uppercase hex digit (use lowercase) at 1:2 of <bytearray-invalid-uppercase-hex.nay>"},
    {"character_invalid_asterisk", "character-invalid-asterisk.nay", "* item\n", 7, "Unexpected character \"*\" at 1:1 of <character-invalid-asterisk.nay>"},
    {"character_invalid_dollar", "character-invalid-dollar.nay", "$\n", 2, "Unexpected character \"$\" at 1:1 of <character-invalid-dollar.nay>"},
    {"comment_only", "comment-only.nay", "# comment\n", 10, "No value found in document <comment-only.nay>"},
    {"document_invalid_extra_content", "document-invalid-extra-content.nay", "\"value\"\nextra\n", 14, "Unexpected extra content at 2:1 of <document-invalid-extra-content.nay>"},
    {"illegal_no_space_after_colon", "illegal-no-space-after-colon.nay", "key:value\n", 10, "Expected space after \":\" at 1:4 of <illegal-no-space-after-colon.nay>"},
    {"illegal_no_space_after_comma", "illegal-no-space-after-comma.nay", "[1,2, 3]\n", 9, "Expected space after \",\" at 1:3 of <illegal-no-space-after-comma.nay>"},
    {"illegal_space_after_brace", "illegal-space-after-brace.nay", "{ a: 1}\n", 8, "Unexpected space after \"{\" at 1:2 of <illegal-space-after-brace.nay>"},
    {"illegal_space_after_colon", "illegal-space-after-colon.nay", "key:  value\n", 12, "Unexpected space after \":\" at 1:6 of <illegal-space-after-colon.nay>"},
    {"illegal_space_before_angle", "illegal-space-before-angle.nay", "<cafe >\n", 8, "Unexpected space before \">\" at 1:6 of <illegal-space-before-angle.nay>"},
    {"illegal_space_before_brace", "illegal-space-before-brace.nay", "{a: 1 }\n", 8, "Unexpected space before \"}\" at 1:6 of <illegal-space-before-brace.nay>"},
    {"indent_invalid_unexpected_number", "indent-invalid-unexpected-number.nay", "  1\n", 4, "Unexpected indent at 1:1 of <indent-invalid-unexpected-number.nay>"},
    {"mixed_depth_nesting_2_invalid_bare_word", "mixed-depth-nesting-2-invalid-bare-word.nay", "- a:\n    b:\n      - 1\n      - 2\n  c: 3\n- - d\n  - e:\n      f: 4\n", 63, "Unexpected character \"d\" at 6:3 of <mixed-depth-nesting-2-invalid-bare-word.nay>"},
    {"not_a_string", "not-a-string.nay", "hello\n", 6, "Unexpected character \"h\" at 1:1 of <not-a-string.nay>"},
    {"number_float_invalid_space_after_dot", "number-float-invalid-space-after-dot.nay", "1. 0\n", 5, "Unexpected space in number at 1:3 of <number-float-invalid-space-after-dot.nay>"},
    {"number_float_invalid_space_before_dot", "number-float-invalid-space-before-dot.nay", "1 .0\n", 5, "Unexpected space in number at 1:2 of <number-float-invalid-space-before-dot.nay>"},
    {"number_float_invalid_uppercase_exponent", "number-float-invalid-uppercase-exponent.nay", "1.5E10\n", 7, "Uppercase exponent (use lowercase 'e') at 1:4 of <number-float-invalid-uppercase-exponent.nay>"},
    {"number_property_invalid_next_line", "number-property-invalid-next-line.nay", "i:\n  42\n", 8, "Unexpected indent at 2:1 of <number-property-invalid-next-line.nay>"},
    {"object_inline_invalid_key_symbol", "object-inline-invalid-key-symbol.nay", "{@: 1}\n", 7, "Invalid key at 1:1 of <object-inline-invalid-key-symbol.nay>"},
    {"object_inline_invalid_missing_colon", "object-inline-invalid-missing-colon.nay", "{a 1}\n", 6, "Expected colon after key at 1:1 of <object-inline-invalid-missing-colon.nay>"},
    {"object_inline_invalid_multiline", "object-inline-invalid-multiline.nay", "{\n  \"a\": 1\n}\n", 13, "Unexpected newline in inline object at 1:1 of <object-inline-invalid-multiline.nay>"},
    {"object_inline_invalid_space_inside", "object-inline-invalid-space-inside.nay", "objectName: { }\n", 16, "Unexpected space after \"{\" at 1:14 of <object-inline-invalid-space-inside.nay>"},
    {"object_inline_invalid_tab", "object-inline-invalid-tab.nay", "key:\0111\n", 7, "Tab not allowed (use spaces) at 1:5 of <object-inline-invalid-tab.nay>"},
    {"object_inline_property_invalid_next_line", "object-inline-property-invalid-next-line.nay", "i:\n  {a: 1}\n", 12, "Unexpected indent at 2:1 of <object-inline-property-invalid-next-line.nay>"},
    {"object_invalid_empty_value", "object-invalid-empty-value.nay", "name:\n", 6, "Expected value after property at 1:6 of <object-invalid-empty-value.nay>"},
    {"object_multiline_invalid_key_char_space", "object-multiline-invalid-key-char-space.nay", "key name: 1\n", 12, "Invalid key character at 1:4 of <object-multiline-invalid-key-char-space.nay>"},
    {"object_multiline_invalid_key_space", "object-multiline-invalid-key-space.nay", "key : 1\n", 8, "Unexpected space before \":\" at 1:4 of <object-multiline-invalid-key-space.nay>"},
    {"object_multiline_invalid_quoted_key_space_after_colon_single", "object-multiline-invalid-quoted-key-space-after-colon-single.nay", "'key':  1\n", 10, "Unexpected space after \":\" at 1:8 of <object-multiline-invalid-quoted-key-space-after-colon-single.nay>"},
    {"object_multiline_invalid_quoted_key_space_after_colon", "object-multiline-invalid-quoted-key-space-after-colon.nay", "\"key\":  1\n", 10, "Unexpected space after \":\" at 1:8 of <object-multiline-invalid-quoted-key-space-after-colon.nay>"},
    {"object_multiline_invalid_quoted_key_space_before_colon_single", "object-multiline-invalid-quoted-key-space-before-colon-single.nay", "'key' : 1\n", 10, "Unexpected space before \":\" at 1:6 of <object-multiline-invalid-quoted-key-space-before-colon-single.nay>"},
    {"object_multiline_invalid_quoted_key_space_before_colon", "object-multiline-invalid-quoted-key-space-before-colon.nay", "\"key\" : 1\n", 10, "Unexpected space before \":\" at 1:6 of <object-multiline-invalid-quoted-key-space-before-colon.nay>"},
    {"object_multiline_invalid_value_space", "object-multiline-invalid-value-space.nay", "key:  1\n", 8, "Unexpected space after \":\" at 1:6 of <object-multiline-invalid-value-space.nay>"},
    {"string_block_invalid_empty", "string-block-invalid-empty.nay", "name: `\n`\n", 10, "Empty block string not allowed (use \"\" or \"\\n\" explicitly)"},
    {"string_block_invalid_tab", "string-block-invalid-tab.nay", "message: `\n  hello\011world\n", 25, "Tab not allowed (use spaces) at 2:8 of <string-block-invalid-tab.nay>"},
    {"string_block_invalid_trailing_space", "string-block-invalid-trailing-space.nay", "message: `\n  hello world \n", 26, "Unexpected trailing space at 2:14 of <string-block-invalid-trailing-space.nay>"},
    {"string_block_property_invalid_leader_next_line", "string-block-property-invalid-leader-next-line.nay", "i:\n  `\n    Should\n    not\n    be.\n", 34, "Unexpected indent at 2:1 of <string-block-property-invalid-leader-next-line.nay>"},
    {"string_block_property_invalid_same_line", "string-block-property-invalid-same-line.nay", "message: ` Hello\n  World\n", 25, "Expected newline after block leader in property"},
    {"string_inline_doublequote_invalid_escape_x", "string-inline-doublequote-invalid-escape-x.nay", "\"\\x\"\n", 5, "Bad escaped character at 1:3 of <string-inline-doublequote-invalid-escape-x.nay>"},
    {"string_inline_doublequote_invalid_unicode_empty", "string-inline-doublequote-invalid-unicode-empty.nay", "\"\\u{}\"\n", 7, "Bad Unicode escape at 1:4 of <string-inline-doublequote-invalid-unicode-empty.nay>"},
    {"string_inline_doublequote_invalid_unicode_hex", "string-inline-doublequote-invalid-unicode-hex.nay", "\"\\u{ZZZZ}\"\n", 11, "Bad Unicode escape at 1:4 of <string-inline-doublequote-invalid-unicode-hex.nay>"},
    {"string_inline_doublequote_invalid_unicode_old_syntax", "string-inline-doublequote-invalid-unicode-old-syntax.nay", "\"\\u0041\"\n", 9, "Bad escaped character at 1:3 of <string-inline-doublequote-invalid-unicode-old-syntax.nay>"},
    {"string_inline_doublequote_invalid_unicode_outofrange", "string-inline-doublequote-invalid-unicode-outofrange.nay", "\"\\u{110000}\"\n", 13, "Unicode code point out of range at 1:4 of <string-inline-doublequote-invalid-unicode-outofrange.nay>"},
    {"string_inline_doublequote_invalid_unicode_surrogate", "string-inline-doublequote-invalid-unicode-surrogate.nay", "\"\\u{D800}\"\n", 11, "Illegal surrogate at 1:4 of <string-inline-doublequote-invalid-unicode-surrogate.nay>"},
    {"string_inline_doublequote_invalid_unicode_toolong", "string-inline-doublequote-invalid-unicode-toolong.nay", "\"\\u{1234567}\"\n", 14, "Bad Unicode escape at 1:4 of <string-inline-doublequote-invalid-unicode-toolong.nay>"},
    {"string_inline_invalid_control_char", "string-inline-invalid-control-char.nay", "\"hello\007world\"\n", 14, "Forbidden code point U+0007 at 1:7 of <string-inline-invalid-control-char.nay>"},
    {"string_inline_invalid_multiline", "string-inline-invalid-multiline.nay", "\"hello\nworld\"\n", 14, "Unterminated string at 1:6 of <string-inline-invalid-multiline.nay>"},
    {"string_inline_property_invalid_next_line", "string-inline-property-invalid-next-line.nay", "i:\n  \"hello\"\n", 13, "Unexpected indent at 2:1 of <string-inline-property-invalid-next-line.nay>"},
    {"unicode_invalid_bom", "unicode-invalid-bom.nay", "\357\273\277x\n", 5, "Illegal BOM at 1:1 of <unicode-invalid-bom.nay>"},
    {"unicode_invalid_c0_bel", "unicode-invalid-c0-bel.nay", "\007\n", 2, "Forbidden code point U+0007 at 1:1 of <unicode-invalid-c0-bel.nay>"},
    {"unicode_invalid_c0_bs", "unicode-invalid-c0-bs.nay", "\010\n", 2, "Forbidden code point U+0008 at 1:1 of <unicode-invalid-c0-bs.nay>"},
    {"unicode_invalid_c0_cr", "unicode-invalid-c0-cr.nay", "\015\n", 2, "Forbidden code point U+000D at 1:1 of <unicode-invalid-c0-cr.nay>"},
    {"unicode_invalid_c0_ff", "unicode-invalid-c0-ff.nay", "\014\n", 2, "Forbidden code point U+000C at 1:1 of <unicode-invalid-c0-ff.nay>"},
    {"unicode_invalid_c0_nak", "unicode-invalid-c0-nak.nay", "\025\n", 2, "Forbidden code point U+0015 at 1:1 of <unicode-invalid-c0-nak.nay>"},
    {"unicode_invalid_c0_null", "unicode-invalid-c0-null.nay", "\000\n", 2, "Forbidden code point U+0000 at 1:1 of <unicode-invalid-c0-null.nay>"},
    {"unicode_invalid_c0_so", "unicode-invalid-c0-so.nay", "\016\n", 2, "Forbidden code point U+000E at 1:1 of <unicode-invalid-c0-so.nay>"},
    {"unicode_invalid_c0_us", "unicode-invalid-c0-us.nay", "\037\n", 2, "Forbidden code point U+001F at 1:1 of <unicode-invalid-c0-us.nay>"},
    {"unicode_invalid_c0_vt", "unicode-invalid-c0-vt.nay", "\013\n", 2, "Forbidden code point U+000B at 1:1 of <unicode-invalid-c0-vt.nay>"},
    {"unicode_invalid_c1_apc", "unicode-invalid-c1-apc.nay", "\302\237\n", 3, "Forbidden code point U+009F at 1:1 of <unicode-invalid-c1-apc.nay>"},
    {"unicode_invalid_c1_ri", "unicode-invalid-c1-ri.nay", "\302\215\n", 3, "Forbidden code point U+008D at 1:1 of <unicode-invalid-c1-ri.nay>"},
    {"unicode_invalid_c1_start", "unicode-invalid-c1-start.nay", "\302\200\n", 3, "Forbidden code point U+0080 at 1:1 of <unicode-invalid-c1-start.nay>"},
    {"unicode_invalid_del", "unicode-invalid-del.nay", "\177\n", 2, "Forbidden code point U+007F at 1:1 of <unicode-invalid-del.nay>"},
    {"unicode_invalid_nonchar_1fffe", "unicode-invalid-nonchar-1fffe.nay", "\360\237\277\276\n", 5, "Forbidden code point U+1FFFE at 1:1 of <unicode-invalid-nonchar-1fffe.nay>"},
    {"unicode_invalid_nonchar_1ffff", "unicode-invalid-nonchar-1ffff.nay", "\360\237\277\277\n", 5, "Forbidden code point U+1FFFF at 1:1 of <unicode-invalid-nonchar-1ffff.nay>"},
    {"unicode_invalid_nonchar_fdd0", "unicode-invalid-nonchar-fdd0.nay", "\357\267\220\n", 4, "Forbidden code point U+FDD0 at 1:1 of <unicode-invalid-nonchar-fdd0.nay>"},
    {"unicode_invalid_nonchar_fdda", "unicode-invalid-nonchar-fdda.nay", "\357\267\232\n", 4, "Forbidden code point U+FDDA at 1:1 of <unicode-invalid-nonchar-fdda.nay>"},
    {"unicode_invalid_nonchar_fdef", "unicode-invalid-nonchar-fdef.nay", "\357\267\257\n", 4, "Forbidden code point U+FDEF at 1:1 of <unicode-invalid-nonchar-fdef.nay>"},
    {"unicode_invalid_nonchar_fffe", "unicode-invalid-nonchar-fffe.nay", "\357\277\276\n", 4, "Forbidden code point U+FFFE at 1:1 of <unicode-invalid-nonchar-fffe.nay>"},
    {"unicode_invalid_nonchar_ffff", "unicode-invalid-nonchar-ffff.nay", "\357\277\277\n", 4, "Forbidden code point U+FFFF at 1:1 of <unicode-invalid-nonchar-ffff.nay>"},
    {"whitespace_invalid_tab", "whitespace-invalid-tab.nay", "\011x\n", 3, "Tab not allowed (use spaces) at 1:1 of <whitespace-invalid-tab.nay>"},
    {"whitespace_invalid_trailing_space", "whitespace-invalid-trailing-space.nay", "key: 1 \n", 8, "Unexpected trailing space at 1:7 of <whitespace-invalid-trailing-space.nay>"},
    {NULL, NULL, NULL, 0, NULL}
};

#define ERROR_FIXTURE_COUNT 91

#endif /* FIXTURES_GEN_H */
