//go:build ignore

// gen_fixtures reads test/go/*.go fixture files and generates fixtures_gen_test.go
// The .go fixture files contain raw Go expressions (not full Go source files).
package main

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	testRoot := filepath.Join("..", "test")
	goDir := filepath.Join(testRoot, "go")
	yayDir := filepath.Join(testRoot, "yay")
	outFile := "fixtures_gen_test.go"

	// Find all .go files in test/go/ that have a matching .yay file
	entries, err := os.ReadDir(goDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error reading go fixture dir: %v\n", err)
		os.Exit(1)
	}

	type fixture struct {
		name string
		expr string
	}
	var fixtures []fixture

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") {
			continue
		}

		baseName := strings.TrimSuffix(entry.Name(), ".go")
		yayPath := filepath.Join(yayDir, baseName+".yay")
		if _, err := os.Stat(yayPath); os.IsNotExist(err) {
			continue // No matching .yay file
		}

		goPath := filepath.Join(goDir, entry.Name())
		src, err := os.ReadFile(goPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "error reading %s: %v\n", goPath, err)
			continue
		}

		// The .go file contains a raw Go expression, not a full source file
		expr := strings.TrimSpace(string(src))
		fixtures = append(fixtures, fixture{
			name: baseName,
			expr: expr,
		})
	}

	// Sort by name for deterministic output
	sort.Slice(fixtures, func(i, j int) bool {
		return fixtures[i].name < fixtures[j].name
	})

	// Generate output
	var out bytes.Buffer
	out.WriteString(`// Code generated by go generate; DO NOT EDIT.

package yay

import (
	"math"
	"math/big"
)

// Helper functions for fixture expressions
func NewInt(x int64) *big.Int { return big.NewInt(x) }

func List(items ...any) []any { return items }

func Map(kvs ...any) map[string]any {
	m := make(map[string]any)
	for i := 0; i+1 < len(kvs); i += 2 {
		if k, ok := kvs[i].(string); ok {
			m[k] = kvs[i+1]
		}
	}
	return m
}

var (
	Null   any     = nil
	NaN            = math.NaN()
	Inf            = math.Inf(1)
	NegInf         = math.Inf(-1)
)

var fixtures = map[string]any{
`)

	for _, f := range fixtures {
		out.WriteString(fmt.Sprintf("\t%q: %s,\n", f.name, f.expr))
	}

	out.WriteString(`}
`)

	if err := os.WriteFile(outFile, out.Bytes(), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing %s: %v\n", outFile, err)
		os.Exit(1)
	}

	// Run gofmt on the generated file
	cmd := exec.Command("gofmt", "-w", outFile)
	if err := cmd.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "warning: gofmt failed: %v\n", err)
	}

	fmt.Printf("Generated %s with %d fixtures\n", outFile, len(fixtures))
}
