// Code generated by gen_fixtures.sh; DO NOT EDIT.

package com.kriskowal.yay;

import java.math.BigInteger;
import java.util.*;

/** Generated fixture data for testing. */
public class FixturesGen {

  // Helper methods
  private static List<Object> list(Object... items) {
    return Arrays.asList(items);
  }

  private static Map<String, Object> map(Object... kvs) {
    Map<String, Object> m = new LinkedHashMap<>();
    for (int i = 0; i + 1 < kvs.length; i += 2) {
      m.put((String) kvs[i], kvs[i + 1]);
    }
    return m;
  }

  private static byte[] bytes(int... values) {
    byte[] b = new byte[values.length];
    for (int i = 0; i < values.length; i++) {
      b[i] = (byte) values[i];
    }
    return b;
  }

  private static BigInteger bi(long value) {
    return BigInteger.valueOf(value);
  }

  public static final Map<String, Object> FIXTURES;

  static {
    FIXTURES = new LinkedHashMap<>();
    FIXTURES.put(
        "at-a-glance",
        map(
            "and-objects-too",
            map("from-their-floating-friends", 6.283185307179586, "integers-are-distinct", bi(42)),
            "arrays",
            list("may", "have", "many", "values"),
            "block",
            map(
                "array", list("But", "this", "one's"),
                "bytes", bytes(0xb0, 0xb5, 0xc0, 0xff, 0xfe, 0xfa, 0xca, 0xde),
                "object", map("mine", null),
                "string", "This is a string.\nThere are many like it.\n"),
            "concatenated",
            "I'm not dead yet. I feel happy!",
            "inline",
            map(
                "array", list(Double.POSITIVE_INFINITY, Double.NEGATIVE_INFINITY, Double.NaN),
                "bytes", bytes(0xf3, 0x3d, 0xfa, 0xce),
                "object", map("bigint", bi(1), "float64", 2.0),
                "string", "is concise"),
            "name with spaces",
            "works too",
            "roses-are-red",
            true,
            "unicode-code-point",
            "😀",
            "violets-are-blue",
            false));
    FIXTURES.put("array-inline-bytearray", list(bytes(0xb0, 0xb5), bytes(0xca, 0xfe)));
    FIXTURES.put("array-inline-doublequote-escapes", list("say \"hi\"", "x"));
    FIXTURES.put(
        "array-inline-apostrophe", list("I'm getting better!", "No you're not.", "I feel happy!"));
    FIXTURES.put("array-inline-doublequote", list("And there was much rejoicing.", "yay."));
    FIXTURES.put("array-inline-integers", list(bi(42), bi(404), bi(418)));
    FIXTURES.put(
        "array-inline-nested",
        list(list("I feel happy!", "yay."), list("And there was much rejoicing.", "yay.")));
    FIXTURES.put("array-inline-singlequote", list("a", "b"));
    FIXTURES.put(
        "array-multiline-named",
        map("complaints", list("I didn't vote for you.", "Help, help, I'm being repressed!")));
    FIXTURES.put(
        "array-multiline-nested-multiline-object",
        list(map("x", bi(10), "y", bi(20)), map("x", bi(30), "y", bi(40))));
    FIXTURES.put("array-multiline-nested", list(list("a", "b"), list(bi(1), bi(2))));
    FIXTURES.put("array-multiline-triple-nested", list(list(list("hello"))));
    FIXTURES.put("array-multiline", list(bi(5), bi(3)));
    FIXTURES.put("bigint-one", bi(1));
    FIXTURES.put("boolean-false", false);
    FIXTURES.put("boolean-true", true);
    FIXTURES.put("bytearray-block-basic", bytes(0xb0, 0xb5, 0xc0, 0xff));
    FIXTURES.put("bytearray-block-comment-only", bytes(0xb0, 0xb5, 0xc0, 0xff));
    FIXTURES.put(
        "bytearray-block-deeply-nested",
        map("level1", map("level2", map("data", bytes(0xb0, 0xb5, 0xc0, 0xff)))));
    FIXTURES.put("bytearray-block-hex-and-comment", bytes(0xb0, 0xb5, 0xc0, 0xff));
    FIXTURES.put(
        "bytearray-block-nested-property",
        map("outer", map("data", bytes(0xb0, 0xb5, 0xc0, 0xff, 0xee, 0xfa, 0xca, 0xde))));
    FIXTURES.put("bytearray-block-property-comment", map("data", bytes(0xb0, 0xb5, 0xc0, 0xff)));
    FIXTURES.put(
        "bytearray-block-property",
        map("data", bytes(0xb0, 0xb5, 0xc0, 0xff, 0xee, 0xfa, 0xca, 0xde)));
    FIXTURES.put("bytearray-in-array", list(bytes(0xb0, 0xb5), bytes(0xca, 0xfe)));
    FIXTURES.put("bytearray-in-object", map("a", bytes(0xb0, 0xb5), "b", bytes(0xca, 0xfe)));
    FIXTURES.put("bytearray-inline-empty", bytes());
    FIXTURES.put("bytearray-inline-even", bytes(0xb0, 0xb5, 0xc0, 0xff, 0xee, 0xfa, 0xca, 0xde));
    FIXTURES.put(
        "bytearray-inline-named",
        map("data", bytes(0xb0, 0xb5, 0xc0, 0xff, 0xee, 0xfa, 0xca, 0xde)));
    FIXTURES.put("integer-big-basic", bi(42));
    FIXTURES.put("integer-big-negative", bi(-42));
    FIXTURES.put("integer-big", bi(8675309));
    FIXTURES.put(
        "mixed-depth-nesting-1",
        map("root", map("a", list(bi(1), bi(2)), "b", map("c", list(bi(3)), "d", bi(4)))));
    FIXTURES.put(
        "mixed-depth-nesting-2",
        list(
            map("a", map("b", list(bi(1), bi(2))), "c", bi(3)),
            list("d", map("e", map("f", bi(4))))));
    FIXTURES.put(
        "mixed-depth-nesting-3",
        map(
            "top",
            map(
                "list",
                list(
                    map("bytes", bytes(0xb0, 0xb5), "tag", "x"),
                    map("more", map("inner", bytes(0x0f, 0x0f)))),
                "solo",
                bi(1))));
    FIXTURES.put("nesting-L0-bytes", bytes(0xb0, 0xb5));
    FIXTURES.put("nesting-L0-false", false);
    FIXTURES.put("nesting-L0-float", 3.14);
    FIXTURES.put("nesting-L0-int", bi(42));
    FIXTURES.put("nesting-L0-null", null);
    FIXTURES.put("nesting-L0-strdq", "hello");
    FIXTURES.put("nesting-L0-strsq", "world");
    FIXTURES.put("nesting-L0-true", true);
    FIXTURES.put("nesting-L1-arr-inline", list(bi(42), "hello", bytes(0xb0, 0xb5)));
    FIXTURES.put("nesting-L1-arr-multi", list(bi(42), "hello", bytes(0xb0, 0xb5)));
    FIXTURES.put("nesting-L1-empty-arr", list());
    FIXTURES.put("nesting-L1-empty-obj", map());
    FIXTURES.put("nesting-L1-named-arr", map("a", list(bi(42))));
    FIXTURES.put("nesting-L1-obj-inline", map("a", bi(42), "b", "hello"));
    FIXTURES.put("nesting-L1-obj-multi", map("a", bi(42), "b", "hello", "c", bytes(0xb0, 0xb5)));
    FIXTURES.put(
        "nesting-L2-arr-in-arr-inline", list(list(bi(42), bi(42)), list("hello", "hello")));
    FIXTURES.put("nesting-L2-arr-in-arr-multi", list(list(bi(42), bi(42)), list("hello", "hello")));
    FIXTURES.put(
        "nesting-L2-arr-in-obj-inline",
        map("a", list(bi(42), bi(42)), "b", list("hello", "hello")));
    FIXTURES.put("nesting-L2-arr-in-obj-multi", map("items", list(bi(42), "hello")));
    FIXTURES.put("nesting-L2-blockbytes-in-obj", map("data", bytes(0xb0, 0xb5)));
    FIXTURES.put("nesting-L2-blockstr-in-obj", map("message", "Hello\n"));
    FIXTURES.put("nesting-L2-empty-nested", map("a", map(), "b", list()));
    FIXTURES.put(
        "nesting-L2-obj-in-arr-multi", list(map("a", bi(42), "b", "hello"), map("c", bi(42))));
    FIXTURES.put(
        "nesting-L2-obj-in-obj-inline", map("a", map("x", bi(42)), "b", map("y", "hello")));
    FIXTURES.put(
        "nesting-L2-obj-in-obj-multi",
        map("a", map("x", bi(42), "y", "hello"), "b", map("z", bi(42))));
    FIXTURES.put("nesting-L3-arr-arr-arr-inline", list(list(list("hello"))));
    FIXTURES.put("nesting-L3-arr-arr-arr", list(list(list(bi(42), bi(42)))));
    FIXTURES.put("nesting-L3-arr-arr-obj", list(list(map("a", bi(42), "b", "hello"))));
    FIXTURES.put(
        "nesting-L3-arr-obj-arr",
        list(map("data", list(bi(42), bi(42))), map("data", list("hello", "hello"))));
    FIXTURES.put("nesting-L3-arr-obj-obj", list(map("nested", map("deep", bi(42)))));
    FIXTURES.put(
        "nesting-L3-blockbytes-nested", map("outer", map("inner", map("data", bytes(0xca, 0xfe)))));
    FIXTURES.put("nesting-L3-blockstr-nested", map("outer", map("inner", map("text", "Deep\n"))));
    FIXTURES.put(
        "nesting-L3-mixed-inline-in-multi",
        map("items", list(list(bi(42), bi(42)), list("hello", "hello"))));
    FIXTURES.put(
        "nesting-L3-obj-arr-arr",
        map("matrix", list(list(bi(42), bi(42)), list("hello", "hello"))));
    FIXTURES.put(
        "nesting-L3-obj-arr-obj",
        map(
            "items",
            list(map("name", "hello", "value", bi(42)), map("name", "hello", "value", bi(42)))));
    FIXTURES.put("nesting-L3-obj-obj-arr", map("outer", map("inner", list(bi(42), "hello"))));
    FIXTURES.put("nesting-L3-obj-obj-obj", map("a", map("b", map("c", bi(42), "d", "hello"))));
    FIXTURES.put("null-literal", null);
    FIXTURES.put("number-float-grouped", 6.283185307179586);
    FIXTURES.put("number-float-infinity", Double.POSITIVE_INFINITY);
    FIXTURES.put("number-float-leading-dot", 0.5);
    FIXTURES.put("number-float-nan", Double.NaN);
    FIXTURES.put("number-float-negative-infinity", Double.NEGATIVE_INFINITY);
    FIXTURES.put("number-float-negative-zero", -0.0);
    FIXTURES.put("number-float-trailing-dot", 1.0);
    FIXTURES.put(
        "number-float-exponent",
        map(
            "leading-dot", 50.0,
            "negative-exp", 0.0000314,
            "no-decimal", 6e23,
            "positive-exp", 2.71e8,
            "scientific", 1.5e10));
    FIXTURES.put("number-float", 6.283185307179586);
    FIXTURES.put("number-float-avogadro", 6.022e23);
    FIXTURES.put("object-deeply-nested-empty", map("level1", map("level2", map("level3", map()))));
    FIXTURES.put("object-inline-doublequote-key", map("*", 1.0));
    FIXTURES.put("object-inline-empty", map("empty", map()));
    FIXTURES.put("object-inline-integers", map("answer", bi(42), "error", bi(404)));
    FIXTURES.put("object-inline-mixed", map("name", "Marvin", "mood", "depressed"));
    FIXTURES.put(
        "object-inline-nested",
        map("luggage", map("combination", bi(12345)), "air", list("canned", "Perri-Air")));
    FIXTURES.put("object-inline-singlequote", map("*", 1.0));
    FIXTURES.put("object-multiline-doublequote-key", map("key name", bi(1)));
    FIXTURES.put(
        "object-multiline-nested",
        map("parrot", map("status", "pining for the fjords", "plumage", "beautiful")));
    FIXTURES.put("object-multiline-singlequote-key", map("key-name", bi(2)));
    FIXTURES.put("object-multiline", map("answer", bi(42), "error", bi(404)));
    FIXTURES.put("object-nested-empty-inline", map("outer", map("inner", map())));
    FIXTURES.put("object-nested-empty-property", map("outer", map("inner", map())));
    FIXTURES.put("string-block-deep-indent", map("message", "Line 1\n  Indented\nLine 2\n"));
    FIXTURES.put(
        "string-block-deeply-nested", map("level1", map("level2", map("text", "Hello\nWorld\n"))));
    FIXTURES.put("string-block-empty-middle", "\nI'm getting better!\n\nNo you're not.\n");
    FIXTURES.put(
        "string-block-nested-in-object-and-array",
        map(
            "parrot",
            map(
                "condition",
                "No, no, it's just resting!\n",
                "remarks",
                list(
                    "Remarkable bird, the Norwegian Blue.\nBeautiful plumage, innit?\n",
                    "It's probably pining for the fjords.\nLovely plumage.\n"))));
    FIXTURES.put(
        "string-block-property-empty-middle",
        map("message", "It's not pining!\n\nIt's passed on! This parrot is no more!\n"));
    FIXTURES.put(
        "string-block-property-trailing-empty",
        map("message", "By Grabthar's hammer... what a savings.\n", "next", bi(1)));
    FIXTURES.put(
        "string-block-property",
        map("message", "By Grabthar's hammer, we live to tell the tale.\n"));
    FIXTURES.put("string-block-root-hash", "# this is not a comment\nit is content\n");
    FIXTURES.put(
        "string-block-root-next-line",
        "\nI've calculated your chance of survival,\nbut I don't think you'll like it.\n");
    FIXTURES.put(
        "string-block-root-same-line",
        "I think you ought to know I'm feeling very depressed.\nThis will all end in tears.\n");
    FIXTURES.put("string-block-trailing-empty", "\nHello\n");
    FIXTURES.put("string-inline-doublequote-apostrophe", "I'm getting better!");
    FIXTURES.put("string-inline-doublequote-basic", "This will all end in tears.");
    FIXTURES.put("string-inline-doublequote-escaped-quote", "He said \"yay.\" and left.");
    FIXTURES.put("string-inline-doublequote-escapes", "\"\\/\b\f\n\r\t☺");
    FIXTURES.put("string-inline-doublequote-space", " ");
    FIXTURES.put("string-inline-doublequote-unicode-emoji", "😀");
    FIXTURES.put("string-inline-doublequote-unicode-surrogate-pair", "😀");
    FIXTURES.put("string-inline-singlequote-basic", "Are you suggesting coconuts migrate?");
    FIXTURES.put("string-inline-singlequote-doublequote", "He said \"yay.\" and left.");
    FIXTURES.put("string-multiline-concat", map("confession", "I'm not dead yet. I feel happy!"));
    FIXTURES.put("whitespace-leading-lines", bi(10));
  }
}
