// Code generated by go generate; DO NOT EDIT.

package yay

import (
	"math"
	"math/big"
)

// Helper functions for fixture expressions
func NewInt(x int64) *big.Int { return big.NewInt(x) }

func List(items ...any) []any { return items }

func Map(kvs ...any) map[string]any {
	m := make(map[string]any)
	for i := 0; i+1 < len(kvs); i += 2 {
		if k, ok := kvs[i].(string); ok {
			m[k] = kvs[i+1]
		}
	}
	return m
}

var (
	Null   any = nil
	NaN        = math.NaN()
	Inf        = math.Inf(1)
	NegInf     = math.Inf(-1)
)

var fixtures = map[string]any{
	"array-inline-apostrophe":          []any{"I'm getting better!", "No you're not.", "I feel happy!"},
	"array-inline-bytearray":           []any{[]byte{0xb0, 0xb5}, []byte{0xca, 0xfe}},
	"array-inline-doublequote":         []any{"And there was much rejoicing.", "yay."},
	"array-inline-doublequote-escapes": []any{"say \"hi\"", "x"},
	"array-inline-integers":            []any{big.NewInt(42), big.NewInt(404), big.NewInt(418)},
	"array-inline-nested": []any{
		[]any{"I feel happy!", "yay."},
		[]any{"And there was much rejoicing.", "yay."},
	},
	"array-inline-singlequote": []any{"a", "b"},
	"array-multiline":          []any{big.NewInt(5), big.NewInt(3)},
	"array-multiline-named": map[string]any{
		"complaints": []any{
			"I didn't vote for you.",
			"Help, help, I'm being repressed!",
		},
	},
	"array-multiline-nested": []any{[]any{"a", "b"}, []any{big.NewInt(1), big.NewInt(2)}},
	"array-multiline-nested-multiline-object": []any{
		map[string]any{"x": big.NewInt(10), "y": big.NewInt(20)},
		map[string]any{"x": big.NewInt(30), "y": big.NewInt(40)},
	},
	"array-multiline-triple-nested": []any{[]any{[]any{"hello"}}},
	"at-a-glance": map[string]any{
		"and-objects-too": map[string]any{
			"from-their-floating-friends": 6.283185307179586,
			"integers-are-distinct":       big.NewInt(42),
		},
		"arrays": []any{"may", "have", "many", "values"},
		"block": map[string]any{
			"array":  []any{"But", "this", "one's"},
			"bytes":  []byte{0xb0, 0xb5, 0xc0, 0xff, 0xfe, 0xfa, 0xca, 0xde},
			"object": map[string]any{"mine": nil},
			"string": "This is a string.\nThere are many like it.\n",
		},
		"concatenated": "I'm not dead yet. I feel happy!",
		"inline": map[string]any{
			"array":  []any{math.Inf(1), math.Inf(-1), math.NaN()},
			"bytes":  []byte{0xf3, 0x3d, 0xfa, 0xce},
			"object": map[string]any{"bigint": big.NewInt(1), "float64": 2.0},
			"string": "is concise",
		},
		"name with spaces":   "works too",
		"roses-are-red":      true,
		"unicode-code-point": "😀",
		"violets-are-blue":   false,
	},
	"bigint-one":                   big.NewInt(1),
	"boolean-false":                false,
	"boolean-true":                 true,
	"bytearray-block-basic":        []byte{0xb0, 0xb5, 0xc0, 0xff},
	"bytearray-block-comment-only": []byte{0xb0, 0xb5, 0xc0, 0xff},
	"bytearray-block-deeply-nested": map[string]any{
		"level1": map[string]any{
			"level2": map[string]any{"data": []byte{0xb0, 0xb5, 0xc0, 0xff}},
		},
	},
	"bytearray-block-hex-and-comment": []byte{0xb0, 0xb5, 0xc0, 0xff},
	"bytearray-block-nested-property": map[string]any{
		"outer": map[string]any{
			"data": []byte{0xb0, 0xb5, 0xc0, 0xff, 0xee, 0xfa, 0xca, 0xde},
		},
	},
	"bytearray-block-property": map[string]any{
		"data": []byte{0xb0, 0xb5, 0xc0, 0xff, 0xee, 0xfa, 0xca, 0xde},
	},
	"bytearray-block-property-comment": map[string]any{"data": []byte{0xb0, 0xb5, 0xc0, 0xff}},
	"bytearray-in-array":               []any{[]byte{0xb0, 0xb5}, []byte{0xca, 0xfe}},
	"bytearray-in-object":              map[string]any{"a": []byte{0xb0, 0xb5}, "b": []byte{0xca, 0xfe}},
	"bytearray-inline-empty":           []byte{},
	"bytearray-inline-even":            []byte{0xb0, 0xb5, 0xc0, 0xff, 0xee, 0xfa, 0xca, 0xde},
	"bytearray-inline-named": map[string]any{
		"data": []byte{0xb0, 0xb5, 0xc0, 0xff, 0xee, 0xfa, 0xca, 0xde},
	},
	"integer-big":          big.NewInt(8675309),
	"integer-big-basic":    big.NewInt(42),
	"integer-big-negative": big.NewInt(-42),
	"mixed-depth-nesting-1": map[string]any{
		"root": map[string]any{
			"a": []any{big.NewInt(1), big.NewInt(2)},
			"b": map[string]any{"c": []any{big.NewInt(3)}, "d": big.NewInt(4)},
		},
	},
	"mixed-depth-nesting-2": []any{
		map[string]any{
			"a": map[string]any{"b": []any{big.NewInt(1), big.NewInt(2)}},
			"c": big.NewInt(3),
		},
		[]any{
			"d",
			map[string]any{"e": map[string]any{"f": big.NewInt(4)}},
		},
	},
	"mixed-depth-nesting-3": map[string]any{
		"top": map[string]any{
			"list": []any{
				map[string]any{"bytes": []byte{0xb0, 0xb5}, "tag": "x"},
				map[string]any{"more": map[string]any{"inner": []byte{0x0f, 0x0f}}},
			},
			"solo": big.NewInt(1),
		},
	},
	"nesting-L0-bytes":      []byte{0xb0, 0xb5},
	"nesting-L0-false":      false,
	"nesting-L0-float":      3.14,
	"nesting-L0-int":        big.NewInt(42),
	"nesting-L0-null":       nil,
	"nesting-L0-strdq":      "hello",
	"nesting-L0-strsq":      "world",
	"nesting-L0-true":       true,
	"nesting-L1-arr-inline": []any{big.NewInt(42), "hello", []byte{0xb0, 0xb5}},
	"nesting-L1-arr-multi":  []any{big.NewInt(42), "hello", []byte{0xb0, 0xb5}},
	"nesting-L1-empty-arr":  []any{},
	"nesting-L1-empty-obj":  map[string]any{},
	"nesting-L1-named-arr":  map[string]any{"a": []any{big.NewInt(42)}},
	"nesting-L1-obj-inline": map[string]any{"a": big.NewInt(42), "b": "hello"},
	"nesting-L1-obj-multi":  map[string]any{"a": big.NewInt(42), "b": "hello", "c": []byte{0xb0, 0xb5}},
	"nesting-L2-arr-in-arr-inline": []any{
		[]any{big.NewInt(42), big.NewInt(42)},
		[]any{"hello", "hello"},
	},
	"nesting-L2-arr-in-arr-multi": []any{
		[]any{big.NewInt(42), big.NewInt(42)},
		[]any{"hello", "hello"},
	},
	"nesting-L2-arr-in-obj-inline": map[string]any{
		"a": []any{big.NewInt(42), big.NewInt(42)},
		"b": []any{"hello", "hello"},
	},
	"nesting-L2-arr-in-obj-multi":  map[string]any{"items": []any{big.NewInt(42), "hello"}},
	"nesting-L2-blockbytes-in-obj": map[string]any{"data": []byte{0xb0, 0xb5}},
	"nesting-L2-blockstr-in-obj":   map[string]any{"message": "Hello\n"},
	"nesting-L2-empty-nested":      map[string]any{"a": map[string]any{}, "b": []any{}},
	"nesting-L2-obj-in-arr-multi": []any{
		map[string]any{"a": big.NewInt(42), "b": "hello"},
		map[string]any{"c": big.NewInt(42)},
	},
	"nesting-L2-obj-in-obj-inline": map[string]any{
		"a": map[string]any{"x": big.NewInt(42)},
		"b": map[string]any{"y": "hello"},
	},
	"nesting-L2-obj-in-obj-multi": map[string]any{
		"a": map[string]any{"x": big.NewInt(42), "y": "hello"},
		"b": map[string]any{"z": big.NewInt(42)},
	},
	"nesting-L3-arr-arr-arr":        []any{[]any{[]any{big.NewInt(42), big.NewInt(42)}}},
	"nesting-L3-arr-arr-arr-inline": []any{[]any{[]any{"hello"}}},
	"nesting-L3-arr-arr-obj":        []any{[]any{map[string]any{"a": big.NewInt(42), "b": "hello"}}},
	"nesting-L3-arr-obj-arr": []any{
		map[string]any{"data": []any{big.NewInt(42), big.NewInt(42)}},
		map[string]any{"data": []any{"hello", "hello"}},
	},
	"nesting-L3-arr-obj-obj": []any{
		map[string]any{"nested": map[string]any{"deep": big.NewInt(42)}},
	},
	"nesting-L3-blockbytes-nested": map[string]any{
		"outer": map[string]any{"inner": map[string]any{"data": []byte{0xca, 0xfe}}},
	},
	"nesting-L3-blockstr-nested": map[string]any{
		"outer": map[string]any{"inner": map[string]any{"text": "Deep\n"}},
	},
	"nesting-L3-mixed-inline-in-multi": map[string]any{
		"items": []any{
			[]any{big.NewInt(42), big.NewInt(42)},
			[]any{"hello", "hello"},
		},
	},
	"nesting-L3-obj-arr-arr": map[string]any{
		"matrix": []any{
			[]any{big.NewInt(42), big.NewInt(42)},
			[]any{"hello", "hello"},
		},
	},
	"nesting-L3-obj-arr-obj": map[string]any{
		"items": []any{
			map[string]any{"name": "hello", "value": big.NewInt(42)},
			map[string]any{"name": "hello", "value": big.NewInt(42)},
		},
	},
	"nesting-L3-obj-obj-arr": map[string]any{
		"outer": map[string]any{"inner": []any{big.NewInt(42), "hello"}},
	},
	"nesting-L3-obj-obj-obj": map[string]any{
		"a": map[string]any{"b": map[string]any{"c": big.NewInt(42), "d": "hello"}},
	},
	"null-literal":          nil,
	"number-float":          6.283185307179586,
	"number-float-avogadro": 602200000000000000000000.0,
	"number-float-exponent": map[string]any{
		"leading-dot":  50.0,
		"negative-exp": 0.0000314,
		"no-decimal":   600000000000000000000000.0,
		"positive-exp": 271000000.0,
		"scientific":   15000000000.0,
	},
	"number-float-grouped":           6.283185307179586,
	"number-float-infinity":          math.Inf(1),
	"number-float-leading-dot":       0.5,
	"number-float-nan":               math.NaN(),
	"number-float-negative-infinity": math.Inf(-1),
	"number-float-negative-zero":     math.Copysign(0, -1),
	"number-float-trailing-dot":      1.0,
	"object-deeply-nested-empty": map[string]any{
		"level1": map[string]any{"level2": map[string]any{"level3": map[string]any{}}},
	},
	"object-inline-doublequote-key": map[string]any{"*": 1.0},
	"object-inline-empty":           map[string]any{"empty": map[string]any{}},
	"object-inline-integers":        map[string]any{"answer": big.NewInt(42), "error": big.NewInt(404)},
	"object-inline-mixed":           map[string]any{"mood": "depressed", "name": "Marvin"},
	"object-inline-nested": map[string]any{
		"air":     []any{"canned", "Perri-Air"},
		"luggage": map[string]any{"combination": big.NewInt(12345)},
	},
	"object-inline-singlequote":        map[string]any{"*": 1.0},
	"object-multiline":                 map[string]any{"answer": big.NewInt(42), "error": big.NewInt(404)},
	"object-multiline-doublequote-key": map[string]any{"key name": big.NewInt(1)},
	"object-multiline-nested": map[string]any{
		"parrot": map[string]any{"plumage": "beautiful", "status": "pining for the fjords"},
	},
	"object-multiline-singlequote-key": map[string]any{"key-name": big.NewInt(2)},
	"object-nested-empty-inline":       map[string]any{"outer": map[string]any{"inner": map[string]any{}}},
	"object-nested-empty-property":     map[string]any{"outer": map[string]any{"inner": map[string]any{}}},
	"string-block-deep-indent":         map[string]any{"message": "Line 1\n  Indented\nLine 2\n"},
	"string-block-deeply-nested": map[string]any{
		"level1": map[string]any{"level2": map[string]any{"text": "Hello\nWorld\n"}},
	},
	"string-block-empty-middle": "\nI'm getting better!\n\nNo you're not.\n",
	"string-block-nested-in-object-and-array": map[string]any{
		"parrot": map[string]any{
			"condition": "No, no, it's just resting!\n",
			"remarks": []any{
				"Remarkable bird, the Norwegian Blue.\nBeautiful plumage, innit?\n",
				"It's probably pining for the fjords.\nLovely plumage.\n",
			},
		},
	},
	"string-block-property": map[string]any{
		"message": "By Grabthar's hammer, we live to tell the tale.\n",
	},
	"string-block-property-empty-middle": map[string]any{
		"message": "It's not pining!\n\nIt's passed on! This parrot is no more!\n",
	},
	"string-block-property-trailing-empty": map[string]any{
		"message": "By Grabthar's hammer... what a savings.\n",
		"next":    big.NewInt(1),
	},
	"string-block-root-hash":                           "# this is not a comment\nit is content\n",
	"string-block-root-next-line":                      "\nI've calculated your chance of survival,\nbut I don't think you'll like it.\n",
	"string-block-root-same-line":                      "I think you ought to know I'm feeling very depressed.\nThis will all end in tears.\n",
	"string-block-trailing-empty":                      "\nHello\n",
	"string-inline-doublequote-apostrophe":             "I'm getting better!",
	"string-inline-doublequote-basic":                  "This will all end in tears.",
	"string-inline-doublequote-escaped-quote":          "He said \"yay.\" and left.",
	"string-inline-doublequote-escapes":                "\"\\/\b\f\n\r\t☺",
	"string-inline-doublequote-space":                  " ",
	"string-inline-doublequote-unicode-emoji":          "😀",
	"string-inline-doublequote-unicode-surrogate-pair": "😀",
	"string-inline-singlequote-basic":                  "Are you suggesting coconuts migrate?",
	"string-inline-singlequote-doublequote":            "He said \"yay.\" and left.",
	"string-multiline-concat":                          map[string]any{"confession": "I'm not dead yet. I feel happy!"},
	"whitespace-leading-lines":                         big.NewInt(10),
}
